import './globals.css'
import { Karla } from 'next/font/google'

const karla = Karla({ subsets: ['latin', 'latin-ext'] })

export const metadata = {
  title: 'Tenzies App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={karla.className}>{children}</body>
    </html>
  )
}
