import './globals.css';
import { Karla } from 'next/font/google';

const karla = Karla(
  {
    subsets: [ 'latin', 'latin-ext' ],
    weight: [ '200', '300', '400', '500', '600', '700', '800' ]
  }
);

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={karla.className}>{children}</body>
    </html>
  );
}
